#include <filesystem>
#include <iostream>

#include "CLI11.hpp"
#include "wyag/cli.hpp"
#include "wyag/git_objects.hpp"
#include "wyag/git_repository.hpp"
#include "wyag/ref.hpp"
#include "wyag/utils.hpp"

using Bytes = std::vector<std::uint8_t>;
namespace fs = std::filesystem;

TagBinding register_tag(CLI::App& app, TagOptions& options) {
    TagBinding binding{};
    binding.subcommand = app.add_subcommand("tag", "list or create a new tag");
    auto* name_opt =
        binding.subcommand->add_option("name", options.name, "Tag name.");
    auto* object_opt = binding.subcommand->add_option(
        "[OBJECT_SHA]", options.object_sha, "Object to point at.");
    auto* annotate_opt = binding.subcommand->add_flag(
        "-a", options.is_tag_object, "Create a tag object.");
    object_opt->needs(name_opt);
    annotate_opt->needs(name_opt);
    return binding;
}

void create_tag(const GitRepository& repo, std::string_view name,
                std::string_view object, bool is_tag_object) {
    // Get the GitObject from the object reference
    std::string target = object.empty() ? "HEAD" : std::string{object};
    auto sha = find_object(repo, target, "commit");
    if (!sha) throw std::runtime_error("Target is not a commit.");

    // Create lightweight tag
    if (!is_tag_object) {
        create_ref(repo, "tags/" + std::string{name}, *sha);
        return;
    }

    // Create object tag
    Tag tag{};
    tag.add_header("object", Bytes{sha->begin(), sha->end()});
    std::string type{"commit"};
    tag.add_header("type", Bytes{type.begin(), type.end()});
    tag.add_header("tag", Bytes{name.begin(), name.end()});
    std::string tagger{"Wyag <wyag@example.com>"};
    tag.add_header("tagger", Bytes{tagger.begin(), tagger.end()});
    std::string message{
        "A tag generated by wyag, which won't let you customize the "
        "message!\n"};
    tag.set_message(Bytes{message.begin(), message.end()});

    std::string tag_sha = write_object(tag, &repo);
    create_ref(repo, "tags/" + std::string{name}, tag_sha);
}

int run_tag(const TagOptions& opts) {
    GitRepository repo = find_repo();

    if (opts.name.empty()) {
        // List references
        fs::path path = repo.get_gitdir() / "refs/tags";
        RefDirectory tags = list_repo_refs(repo, path);
        print_refdir(tags, {}, false);
    } else {
        // Create a tag
        create_tag(repo, opts.name, opts.object_sha, opts.is_tag_object);
    }
    return 0;
}
